import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { PrismaClient, Categories, Locations } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Clear the event and related tables before seeding
  await prisma.team.deleteMany();
  await prisma.event.deleteMany();

  // Create the required documents

  const sportsEvents = [
    {
      title: "Badminton Men",
      slug: "badminton-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 24500,
      runnerUpPrize: 14000,
      minPlayers: 5,
      maxPlayers: 7,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/sports/badminton.png",
    },
    {
      title: "Badminton Women",
      slug: "badminton-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 17500,
      runnerUpPrize: 10000,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/badminton.png",
    },
    {
      title: "Basketball Men",
      slug: "basketball-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 42000,
      runnerUpPrize: 24000,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Basketball Court",
      eventImg: "/sports/basketball.png",
    },
    {
      title: "Basketball Women",
      slug: "basketball-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 42000,
      runnerUpPrize: 24000,
      minPlayers: 6,
      maxPlayers: 12,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Basketball Court",
      eventImg: "/images/landing/sports/basketball.png",
    },
    {
      title: "chess",
      slug: "chess",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 21000,
      runnerUpPrize: 12000,
      minPlayers: 4,
      maxPlayers: 6,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/sports/chess.png",
    },
    {
      title: "cricket men",
      slug: "cricket-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-06-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 52500,
      runnerUpPrize: 30000,
      minPlayers: 13,
      maxPlayers: 15,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Cricket Field",
      eventImg: "/sports/cricket.png",
    },
    {
      title: "cricket women",
      slug: "cricket-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 20000,
      runnerUpPrize: 15500,
      minPlayers: 7,
      maxPlayers: 11,
      pricePerPlayer: 449,
      venue: "Shiv Nadar University- Main Arena",
      eventImg: "/images/landing/sports/cricket.png",
    },
    {
      title: "football",
      slug: "football",
      category: Categories.MIXED,
      location: Locations.OUTDOOR,
      dateFrom: "2025-06-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 56000,
      runnerUpPrize: 32000,
      minPlayers: 14,
      maxPlayers: 16,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Football Field",
      eventImg: "/sports/football.png",
    },
    {
      title: "futsal",
      slug: "futsal",
      category: Categories.MIXED,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 35000,
      runnerUpPrize: 20000,
      minPlayers: 8,
      maxPlayers: 10,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Football Field",
      eventImg: "/sports/futsal.png",
    },
    {
      title: "powerlifting Men",
      slug: "powerlifting-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/powerlifting.png",
    },
    {
      title: "powerlifting Women",
      slug: "powerlifting-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/powerlifting.png",
    },
    {
      title: "squash Men",
      slug: "squash-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 21000,
      runnerUpPrize: 12000,
      minPlayers: 3,
      maxPlayers: 6,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/squash.png",
    },
    {
      title: "Squash Women",
      slug: "squash-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3500,
      runnerUpPrize: 2000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/squash.png",
    },
    {
      title: "TT Men",
      slug: "tt-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 17500,
      runnerUpPrize: 10000,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/table_tennis.png",
    },
    {
      title: "TT Women",
      slug: "tt-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 17500,
      runnerUpPrize: 10000,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/table_tennis.png",
    },
    {
      title: "Tennis Men",
      slug: "tennis-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 14000,
      runnerUpPrize: 8000,
      minPlayers: 3,
      maxPlayers: 4,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Tennis Court",
      eventImg: "/images/landing/sports/lawn_tennis.png",
    },
    {
      title: "Tennis Women",
      slug: "tennis-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 14000,
      runnerUpPrize: 8000,
      minPlayers: 3,
      maxPlayers: 4,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Tennis Court",
      eventImg: "/images/landing/sports/lawn_tennis.png",
    },
    {
      title: "vollyball Men",
      slug: "vollyball-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 42000,
      runnerUpPrize: 24000,
      minPlayers: 7,
      maxPlayers: 12,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Vollyball Court",
      eventImg: "/images/landing/sports/volleyball.png",
    },
    {
      title: "Vollyball Women",
      slug: "vollyball-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 42000,
      runnerUpPrize: 24000,
      minPlayers: 7,
      maxPlayers: 12,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Vollyball Court",
      eventImg: "/images/landing/sports/volleyball.png",
    },
    {
      title: "pool",
      slug: "pool",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 7500,
      runnerUpPrize: 6000,
      minPlayers: 2,
      maxPlayers: 3,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/pool.png",
    },
    {
      title: "valorant",
      slug: "valorant",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 7000,
      runnerUpPrize: 4000,
      minPlayers: 5,
      maxPlayers: 6,
      pricePerPlayer: 99,
      venue: "Online",
      eventImg: "/images/landing/sports/valorant.png",
    },
    {
      title: "Rocket League",
      slug: "rocket-league",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3000,
      runnerUpPrize: 1500,
      minPlayers: 2,
      maxPlayers: 2,
      pricePerPlayer: 49,
      venue: "Online",
      eventImg: "/images/landing/sports/rocket-league.png",
    },
    {
      title: "Yoga Men",
      slug: "yoga-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 2000,
      runnerUpPrize: 1500,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/yoga.png",
    },
    {
      title: "Yoga Women",
      slug: "yoga-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 2000,
      runnerUpPrize: 1500,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/yoga.png",
    },
    {
      title: "100m Men",
      slug: "100m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "200m Men",
      slug: "200m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "400m Men",
      slug: "400m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "800m Men",
      slug: "800m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "1500m Men",
      slug: "1500m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "5000m Men",
      slug: "5000m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x100m Men",
      slug: "4x100m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3000,
      runnerUpPrize: 2500,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x400m Men",
      slug: "4x400m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3000,
      runnerUpPrize: 2500,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Shot put Men",
      slug: "shot-put-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Discus Throw Men",
      slug: "discus-throw-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Javelin Throw Men",
      slug: "javelin-throw-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Long Jump Men",
      slug: "long-jump-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "100m Women",
      slug: "100m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "200m Women",
      slug: "200m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "400m Women",
      slug: "400m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "800m Women",
      slug: "800m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "1500m Women",
      slug: "1500m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x100m Women",
      slug: "4x100m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3000,
      runnerUpPrize: 2500,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x400m Women",
      slug: "4x400m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3000,
      runnerUpPrize: 2500,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Shot put Women",
      slug: "shot-put-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Discus Throw Women",
      slug: "discus-throw-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Javelin Throw Women",
      slug: "javelin-throw-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Long Jump Women",
      slug: "long-jump-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 1500,
      runnerUpPrize: 1000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x100m Mixed",
      slug: "4x100m-mixed",
      category: Categories.MIXED,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3000,
      runnerUpPrize: 2500,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x400m Mixed",
      slug: "4x400m-mixed",
      category: Categories.MIXED,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3000,
      runnerUpPrize: 2500,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
  ];

  for (const event of sportsEvents) {
    await prisma.event.create({
      data: {
        name: event.title,
        slug: event.slug,
        category: event.category,
        location: event.location,
        dateFrom: event.dateFrom,
        dateTo: event.dateTo,
        venue: event.venue,
        rules: event.rules,
        winnerPrize: event.winnerPrize,
        runnerUpPrize: event.runnerUpPrize,
        minPlayers: event.minPlayers,
        maxPlayers: event.maxPlayers,
        pricePerPlayer: event.pricePerPlayer,
        eventImg: event.eventImg, // Hardcoded image path
      },
    });
  }

  console.log("Sports events seeded successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
