import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { PrismaClient, Categories, Locations } from "@prisma/client";

const prisma = new PrismaClient();

const athleticsDescription = `
General Athletics Rules:
- All events will follow standard international athletics regulations
- Competitors must be registered and present valid identification
- Each participant can compete in a maximum of 3 individual events
- Finals will be held for each event based on qualification standards
- Disqualification may occur for false starts (after one allowed) or rule violations
- Athletes must compete in proper running attire and shoes
`;

async function main() {
  // Clear the event and related tables before seeding
  await prisma.team.deleteMany();
  await prisma.event.deleteMany();

  // Create the required documents

  const sportsEvents = [
    {
      title: "Badminton Men",
      slug: "badminton-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "Teams to be divided into 4 pools. Top teams to qualify for semifinals. Each match to be best of three games format. Semifinals to be best of five games format.",
      winnerPrize: 38500,
      runnerUpPrize: 22000,
      minPlayers: 5,
      maxPlayers: 7,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/sports/badminton.png",
    },
    {
      title: "Badminton Women",
      slug: "badminton-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "Teams to be divided into 4 pools. Top teams to qualify for semifinals. Each match to be best of three games format. Semifinals to be best of five games format.",
      winnerPrize: 38500,
      runnerUpPrize: 22000,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/badminton.png",
    },
    {
      title: "Basketball Men",
      slug: "basketball-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "FIBA rules applicable. Each quarter will be of 10 minutes with a 2 minutes break between them and a 5-minute break at half time.",
      winnerPrize: 84000,
      runnerUpPrize: 48000,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Basketball Court",
      eventImg: "/sports/basketball.png",
    },
    {
      title: "Basketball Women",
      slug: "basketball-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "FIBA rules applicable. Each quarter will be of 10 minutes with a 2 minutes break between them and a 5-minute break at half time.",
      winnerPrize: 84000,
      runnerUpPrize: 48000,
      minPlayers: 6,
      maxPlayers: 12,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Basketball Court",
      eventImg: "/images/landing/sports/basketball.png",
    },
    {
      title: "chess",
      slug: "chess",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "Master your strategy and outthink your opponent in our thrilling chess competition—where every move matters!",
      winnerPrize: 6000,
      runnerUpPrize: 3000,
      minPlayers: 5,
      maxPlayers: 7,
      pricePerPlayer: 500,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/sports/chess.png",
    },
    {
      title: "cricket men",
      slug: "cricket-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-06-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "The tournament will be played on a knockout basis. Matches will be conducted with white balls. Teams have to play their matches in colored kits.",
      winnerPrize: 52500,
      runnerUpPrize: 30000,
      minPlayers: 13,
      maxPlayers: 15,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Cricket Field",
      eventImg: "/sports/cricket.png",
    },
    {
      title: "cricket women",
      slug: "cricket-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "The tournament will be played on a knockout basis. Matches will be conducted with white balls. Teams have to play their matches in colored kits.",
      winnerPrize: 22000,
      runnerUpPrize: 16500,
      minPlayers: 7,
      maxPlayers: 11,
      pricePerPlayer: 449,
      venue: "Shiv Nadar University- Main Arena",
      eventImg: "/images/landing/sports/cricket.png",
    },
    {
      title: "football",
      slug: "football",
      category: Categories.MIXED,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "The game will be played in accordance with the rules established by FIFA.",
      winnerPrize: 56000,
      runnerUpPrize: 32000,
      minPlayers: 14,
      maxPlayers: 16,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Football Field",
      eventImg: "/sports/football.png",
    },
    {
      title: "futsal",
      slug: "futsal",
      category: Categories.MIXED,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "6 vs 6 format one of which will be the goalkeeper. Duration of matches: 30 minutes (2*15 minutes) with a 10-minute break between halves.",
      winnerPrize: 35500,
      runnerUpPrize: 20000,
      minPlayers: 8,
      maxPlayers: 10,
      pricePerPlayer: 779,
      venue: "Shiv Nadar University- Football Field",
      eventImg: "/sports/futsal.png",
    },
    {
      title: "Squash (Men)",
      slug: "squash-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "Rules of the Squash Rackets Federation of India will be applicable. The tournament shall be played in singles only and on a league-cum knockout basis. The knockout system shall be followed only amongst the first four teams.",
      winnerPrize: 24500,
      runnerUpPrize: 14000,
      minPlayers: 3,
      maxPlayers: 6,
      pricePerPlayer: 775,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/images/landing/sports/squash.png",
    },
    {
      title: "Squash (Women)",
      slug: "squash-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "Rules of the Squash Rackets Federation of India will be applicable. The tournament shall be played in singles only and on a league-cum knockout basis. The knockout system shall be followed only amongst the first four teams. Women’s squash will be an individual event.",
      winnerPrize: 24500,
      runnerUpPrize: 14000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 775,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/images/landing/sports/squash.png",
    },
    {
      title: "Table Tennis (Men)",
      slug: "table-tennis-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "AIU (Association of Indian Universities) Rules will be followed for the tournament. The format of the match for Men will be a team event having 3 SINGLES and 2 REVERSE SINGLES.",
      winnerPrize: 35000,
      runnerUpPrize: 20000,
      minPlayers: 4,
      maxPlayers: 5,
      pricePerPlayer: 775,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/images/landing/sports/table_tennis.png",
    },
    {
      title: "Table Tennis (Women)",
      slug: "table-tennis-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "AIU (Association of Indian Universities) Rules will be followed for the tournament. The format of the match for Women will be a team event having 2 SINGLES and 1 DOUBLES.",
      winnerPrize: 35000,
      runnerUpPrize: 20000,
      minPlayers: 4,
      maxPlayers: 5,
      pricePerPlayer: 775,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/images/landing/sports/table_tennis.png",
    },
    {
      title: "Tennis (Men)",
      slug: "tennis-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "International Tennis Federation rules will be applicable. Tournament will be played in singles and doubles format.",
      winnerPrize: 28000,
      runnerUpPrize: 16000,
      minPlayers: 3,
      maxPlayers: 4,
      pricePerPlayer: 775,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/images/landing/sports/lawn_tennis.png",
    },
    {
      title: "Tennis (Women)",
      slug: "tennis-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "International Tennis Federation rules will be applicable. Tournament will be played in singles and doubles format.",
      winnerPrize: 28000,
      runnerUpPrize: 16000,
      minPlayers: 3,
      maxPlayers: 4,
      pricePerPlayer: 775,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/images/landing/sports/lawn_tennis.png",
    },
    {
      title: "Volleyball (Men)",
      slug: "volleyball-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "International laws would be followed according to FIVB rules. All league matches will be of 3 sets. In the case of a 1-1 tie, the deciding 3rd set is played to 15 points. The semi-finals and final will be of 5 sets.",
      winnerPrize: 84000,
      runnerUpPrize: 48000,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 775,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/images/landing/sports/volleyball.png",
    },
    {
      title: "Volleyball (Women)",
      slug: "volleyball-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "International laws would be followed according to FIVB rules. All league matches will be of 3 sets. In the case of a 1-1 tie, the deciding 3rd set is played to 15 points. The semi-finals and final will be of 5 sets.",
      winnerPrize: 84000,
      runnerUpPrize: 48000,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 775,
      venue: "Shiv Nadar University Sports Complex",
      eventImg: "/images/landing/sports/volleyball.png",
    },
    {
      title: "Powerlifting (Men)",
      slug: "powerlifting-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "The competition will adhere to a classic 3-lift sequence in the following order: 1. Squats 2. Bench Press 3. Deadlift. The competition will follow the IPF Powerlifting Rulebook 2024 for rules on performance and disqualification.",
      winnerPrize: 3000,
      runnerUpPrize: 2000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/powerlifting.png",
    },
    {
      title: "powerlifting Women",
      slug: "powerlifting-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "The competition will adhere to a classic 3-lift sequence in the following order: 1. Squats 2. Bench Press 3. Deadlift. The competition will follow the IPF Powerlifting Rulebook 2024 for rules on performance and disqualification.",
      winnerPrize: 3000,
      runnerUpPrize: 2000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/powerlifting.png",
    },
    {
      title: "100m Men",
      slug: "100m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "200m Men",
      slug: "200m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "400m Men",
      slug: "400m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "800m Men",
      slug: "800m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "1500m Men",
      slug: "1500m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "5000m Men",
      slug: "5000m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x100m Men",
      slug: "4x100m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x400m Men",
      slug: "4x400m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Shot put Men",
      slug: "shot-put-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Discus Throw Men",
      slug: "discus-throw-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Javelin Throw Men",
      slug: "javelin-throw-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "Standard IAAF rules apply. Each competitor will be given 6 attempts to achieve maximum distance.",
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Long Jump Men",
      slug: "long-jump-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "100m Women",
      slug: "100m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "200m Women",
      slug: "200m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "400m Women",
      slug: "400m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "800m Women",
      slug: "800m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "1500m Women",
      slug: "1500m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x100m Women",
      slug: "4x100m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x400m Women",
      slug: "4x400m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Shot put Women",
      slug: "shot-put-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Discus Throw Women",
      slug: "discus-throw-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Javelin Throw Women",
      slug: "javelin-throw-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "Standard IAAF rules apply. Each competitor will be given 6 attempts to achieve maximum distance.",
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "Long Jump Women",
      slug: "long-jump-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 37500,
      runnerUpPrize: 25000,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 249,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x100m Mixed",
      slug: "4x100m-mixed",
      category: Categories.MIXED,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 3000,
      runnerUpPrize: 2500,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "4x400m Mixed",
      slug: "4x400m-mixed",
      category: Categories.MIXED,
      location: Locations.OUTDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 3000,
      runnerUpPrize: 2500,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University-horse stables ground",
      eventImg: "/images/landing/sports/athletics.png",
    },
    {
      title: "valorant",
      slug: "valorant",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules:
        "Get ready to dominate the battlefield in our high-stakes Valorant online competition—where every shot counts!",
      winnerPrize: 6000,
      runnerUpPrize: 3000,
      minPlayers: 5,
      maxPlayers: 6,
      pricePerPlayer: 99,
      venue: "Online",
      eventImg: "/images/landing/sports/valorant.png",
    },
    {
      title: "Rocket League",
      slug: "rocket-league",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 3000,
      runnerUpPrize: 1500,
      minPlayers: 2,
      maxPlayers: 2,
      pricePerPlayer: 49,
      venue: "Online",
      eventImg: "/images/landing/sports/rocket-league.png",
    },
    {
      title: "Yoga Men",
      slug: "yoga-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 2000,
      runnerUpPrize: 1500,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/yoga.png",
    },
    {
      title: "Yoga Women",
      slug: "yoga-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2025-07-11T00:00:00Z",
      dateTo: "2025-09-11T23:59:59Z",
      rules: "",
      winnerPrize: 2000,
      runnerUpPrize: 1500,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 499,
      venue: "Shiv Nadar University- Indoor Sports Complex",
      eventImg: "/images/landing/sports/yoga.png",
    },
  ];

  for (const event of sportsEvents) {
    await prisma.event.create({
      data: {
        name: event.title,
        slug: event.slug,
        category: event.category,
        location: event.location,
        dateFrom: event.dateFrom,
        dateTo: event.dateTo,
        venue: event.venue,
        rules: event.rules,
        winnerPrize: event.winnerPrize,
        runnerUpPrize: event.runnerUpPrize,
        minPlayers: event.minPlayers,
        maxPlayers: event.maxPlayers,
        pricePerPlayer: event.pricePerPlayer,
        eventImg: event.eventImg, // Hardcoded image path
      },
    });
  }

  console.log("Sports events seeded successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });